# docker-compose.yml
version: '3.5'
services:
  db:
    restart: unless-stopped
    build:
      context: postgres/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
  adminer:
    restart: unless-stopped
    build:
      context: adminer/
    ports:
      - 8080:8080
volumes:
  postgres-volume: